### PR TITLE
CSV Export numberFormatter

### PR DESCRIPTION
**Pull request by ggrote**
# New Pull Request

We needed the numbers in a csv export to be formatted correctly with a comma as a decimal separator. So I thought it would be a good way to implement a numberFormatter like the dateFormatter for the CSV Export.

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

Sorry, I don't know how to write unit tests.

### CODE REVIEW

**Comment by junedchhipa** [comment]
@ggrote Thanks for the contribution. Shouldn't you also set the numberFormatter here as well? [ln#307](https://github.com/apexcharts/apexcharts.js/pull/4538/files#diff-5b1bb0e80c50f9788f49da9cc9b7568003a24cc70817ba42c0e2803f6dff0177R307) and [ln#387](https://github.com/apexcharts/apexcharts.js/pull/4538/files#diff-5b1bb0e80c50f9788f49da9cc9b7568003a24cc70817ba42c0e2803f6dff0177R387)

**Comment by ggrote** [comment]
I thought these lines are only for categories. But you are right they can be numbers too.

**Comment by ggrote** [comment]
I think that should be it. Any chance to integrate the changes?
And maybe you can answer my question at vue3-apexcharts (https://github.com/apexcharts/vue3-apexcharts/issues/106)?

**Comment by ggrote** [comment]
Okay, how do you want to know which value should be formatted? By type?
Anything I can help you with?

**Review by junedchhipa — APPROVED** [review]

**Comment by junedchhipa** [comment]
instead of dateFormatter and numberFormatter, I have used the correct namings.
The new properties will be `categoryFormatter` for x value and `valueFormatter` and y values

```
chart: {
   toolbar: {
       export: {
            csv: {
              categoryFormatter: (cat) => (cat),
              valueFormatter: (val) => (val),
            },
        },
    }
}
```

Docs will be updated after the new release

**Pull request merged**
