### PR TITLE
fix multiple brush targets

### PR DESCRIPTION
**Pull request by AurelReb**
# New Pull Request

This commit fixes 'multiple brush targets' feature. Before it updated only the last target in the array of targets because the brush selection function was defined to update the last target in the array. Now this function updates each target of the array.

Fixes AurelReb@9454ba9 committed by @junedchhipa in january

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by junedchhipa** [comment]
Thanks for the PR.

Can you please re-add the images which you deleted? Those images are used in dashboard samples.

**Comment by AurelReb** [comment]
oh sorry, it was a not voluntary deletion.
Btw, I added back your commit which fixed the sync with grouped charts.

**Comment by junedchhipa** [comment]
Thanks!
Looks good.

**Comment by AurelReb** [comment]
Just noticed that when we add forceNiceScale on the brush chart, the autoscale on target charts is also with nice values! The result is perfect, Thank you

**Pull request merged**
