### PR TITLE
fix: fixed autoScaleY for all zero values in array

### PR DESCRIPTION
**Pull request by lucacapocci94-dev**
# New Pull Request

My fix contain the solution at autoScaleYaxis that for all zero values in a series not show line chart

Fixes # (issue)

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by junedchhipa** [comment]
What problem does this PR solve? Can you create a Codepen illustrating the fix?

**Comment by junedchhipa** [comment]
Instead of checking min === 0 and max === 0 separately, you should check both in a single condition.

**Comment by lucacapocci94-dev** [comment]
The problem it solves is the following: When there are all zero values ​​in a series, I add an arbitrary minimum and maximum so that the line with zero values ​​is visible.  While to date the autoScale, as I have seen in the code, multiplying a minimum and a maximum equal to zero by "0.9" or "1.1", will always be 0 and therefore the line will never be visible.  Also I agree to put a single control because it is even fairer, i.e. only when in a series the minimum and maximum of the values ​​are both equal to zero, an arbitrary value must be set.

**Comment by lucacapocci94-dev** [comment]
https://user-images.githubusercontent.com/82463600/175947191-6586f93f-39ee-4975-89a1-311c66e0096c.mov

With video you understand better

**Review by junedchhipa — APPROVED** [review]

**Pull request merged**
