### PR TITLE
Fix CSP issues

### LINKED ISSUE #727: Is it possible to disable unsafe inline style in ApexCharts ?
Hei,

We use ApexCharts with Content Security Policy, and it seems that the option `style-src 'self' 'unsafe-inline'`.

If not the following error happens and the charts layouts are broken.

```
Refused to apply inline style because it violates the following Content Security Policy directive
```

Is it possible to use ApexCharts without unsafe inline styles ?

### PR DESCRIPTION
**Pull request by spotman**
# New Pull Request

Fix Content Security Policy isses caused by injecting CSS styles into DOM. CSS instructions extracted from Legend module and DetectElementResize util. Tested in browser with `line` chart.
Local run `npm run test` is crashed so please run tests on your side before merging.

Fixes #727 

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by spotman** [comment]
Added missing styles for Legend module.

**Comment by junedchhipa** [comment]
Thanks for the PR. I will take a look soon.

**Comment by junedchhipa** [comment]
The line charts are broken when I tested your code.
Please check `/src/samples/vanilla-js/line/dashed-line.html`

Screen Shot 2019-10-03 at 12 00 38 AM

**Comment by spotman** [comment]
@junedchhipa samples are using `dist` version of the lib, but I had not build it (`npm run test` and `npm run build` are crashing). I'm using `src/apexcharts.js` as an entrypoint for webpack in my local CSP tests - everything is working (different types of charts was checked).

**Comment by junedchhipa** [comment]
When you run ‘npm rum dev’, it automatically creates a build file in the ‘dist’ directory.
I will pull your fork and check again.

**Comment by spotman** [comment]
`npm run dev` does not make builds for webpack + CSS file `/dist/apexcharts` is not touched (it has no updated instructions from `/src/assets/apexcharts.css`). And `npm run build` is crashing on my workstation so I've used `/src/` version for testing.

I think that building workflow needs to be improved.

**Comment by junedchhipa** [comment]
We need to test with `/dist/apexcharts.js` to ensure it works correctly in the final build as well.

**Comment by junedchhipa** [comment]
Sorry, the error for which I posted the screenshot was due to some other code.
I have checked your code again and it works fine :)

My bad!
Merged your PR.

**Comment by junedchhipa** [comment]
Can you please do a quick test on IE11? How does the legend look there?

**Comment by spotman** [comment]
@junedchhipa I have no access to Windows workstations with IE but I bet that everything is OK coz the styling logic had not changed.

**Comment by junedchhipa** [comment]
Hi @spotman 
I had to revert 1 change (Legend styles and inject back into JS) because it broke the exporting of the SVG/PNG (issue #992).

You can test the current version 3.10.0 and see how legend looks when exporting in a multi-series chart.

**Comment by spotman** [comment]
Hi @junedchhipa
My bad, I had not tested export coz whole menu does not work in `src` version of lib.
Is there any way to export SVG/PNG without injecting styles in the DOM directly?

**Comment by blueeDeveloper** [comment]
@junedchhipa @spotman  - I am getting below error on my console. i have the latest version of apexcharts. 

Refused to apply inline style because it violates the following Content Security Policy directive: "default-src 'self' *.apple.com". Either the 'unsafe-inline' keyword, a hash ('sha256-We76yQ6BbUqy3OL7pB4AiChSOtAH/BdDsZ0Z+MzXvD0='), or a nonce ('nonce-...') is required to enable inline execution. Note also that 'style-src' was not explicitly set, so 'default-src' is used as a fallback.

Is there a way to get rid of this error. Due to this error, the styling of the stacked bar chart is a little messed up.

**Comment by spotman** [comment]
@blueeDeveloper Inline styles is a lazy way of programming, so it's faster to implement. Most third-party tools violate CSP rules in some way and their maintainers do not want to invest their time into CSP compatibility. I've made an attempt to make this library CSP compatible, but it has complicated logic for positioning. You may check latest commits in my fork https://github.com/spotman/apexcharts.js It would be nice to fix this library but I've gave up already.

**Pull request merged**
