### PR TITLE
Bugfix: multiple lines added to a stack bar chart also stack

### LINKED ISSUE #907: mixed chart with stacked bars and line series - incorrect line draw
I noticed that when I have mixed stacked chart with bars and line series, the line drawings are stacked.
I got 2 line series. Second line drawing does not correspond to provided values. I get it that chart type is stacked but it should apply only for bar (or column) series.

## Codepen
Here is example:
https://codesandbox.io/s/react-basic-example-o3erk

## Explanation

- What is the behavior you expect?
Draw not stacked lines. Values in tooltip are correct but drawing is not.
- What is happening instead?
Lines series are stacked.
- What error message are you getting?
No error.

### PR DESCRIPTION
**Pull request by iameddz**
# New Pull Request

**Fixes #907 and #2076**

When adding multiple lines to an existing stack bar chart, the lines are also stacked rather than being expressed independently. That is, where line series 1 has a value of 10 and line series 2 has a value of 5 series 2 will be plotted at 15, not 5.

### New Options:
chart.stackOnlyBar = true
tooltip.hideEmptyShared = true

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Review by CharlesLB — APPROVED** [review]

**Review by AntoineDrsl — APPROVED** [review]

**Review by ChrystianDeMatos — APPROVED** [review]

**Comment by javierarocena** [comment]
👀

**Comment by javierarocena** [comment]
Could someone please merge this?

**Comment by aminebelmahi** [comment]
Why is this PR closed when it could a very good fix for the library?

**Comment by nikolaVlad** [comment]
Are this will be merged ?

**Comment by dvbeek** [comment]
I was waiting / following this pull request, but it seems the problem has been solved in another pull request: https://github.com/apexcharts/apexcharts.js/pull/3891.

So in new versions, this should no longer be a problem.

**Pull request closed without merging**
