### PR TITLE
WIP: Build improvements

### PR DESCRIPTION
**Pull request by cstlaurent**
Hi,

This is a follow-up PR for the issue #262 addressing some of the mentioned topics.

### Improvements

- For better code standardization, Eslint was properly configured with Prettier which allows automatic formatting of code in the future. (I did not apply the Eslint fixes in this PR since it would be hard to understand what has been done. Will do in future PR.)
- Build pipeline has been reduced from Webpack, Gulp, and Rollup to only Rollup. The new pipeline was mostly inspired by what is done in the vue.js project.
- The build now creates proper UMD, UMD + minified, ESM and CJS output files with proper package.json configurations. This modification allows all usage scenarios, UMD can be used directly in browsers, ESM with the latest build tools and CJS with older ones.
- Package.json entries were added for jsdelivr and unpkg. This allows CDNs to choose the proper UMD build output.
- Dev dependencies were cleaned up and locked to a specified version (current latest) so that it is possible to have reproducible builds.
- All `require` and `module.exports` have been removed and converted to ecmascript modules `import/export` in all src and tests folders. The mix and match use of cjs and esm was probably the root cause of all build issues.

### Issues/Questions

- There seems to be a limitation/bug with Babel 7 which causes some tests, and the edge/IE build to fail. I’m still investigating the source of the issue.
- I’m not sure how the locales files are dealt with… I don’t see any code/way to load them dynamically, so I’m not sure what to do with them with the build.
- Some npm scripts have changed, but you would still use npm run build to generate the output.
- I’m not sure how you create new releases, so I did not commit the new files under the dist/ folder, so they would need to be generated for the new version.

There seem to be no breaking changes, but I think creating a pre-release npm package would be better so we can test all the packages components correctly using npm/yarn and validate that everything works as it should.

### CODE REVIEW

**Comment by junedchhipa** [comment]
Excellent work!
I just reviewed the commits and going to merge it. I will also look into the IE build issue.
Thanks.

**Comment by junedchhipa** [comment]
For new releases, I follow the simple steps.
```bash
npm run build
git commit - new build > push
npm version patch|minor|major
npm publish
```

**Comment by junedchhipa** [comment]
After trying fixes for IE11 for several hours, injecting polyfills and finally getting it to work, I decided to abandon IE11 support and put a notice in the README to include a polyfill if IE11 support is required.
As to including polyfills increased the minified size by 90 KB, I think is not worth it just for IE11.

Hence, the next release will be a major update 3.0.
Everything else worked really well

**Comment by cstlaurent** [comment]
Thanks for merging the PR!

I think its the way to go too for IE. Having a 90 KB size/parse hit for everyone just to support it is hard to justify.

**Comment by junedchhipa** [comment]
@cstlaurent I think, the new build configuration has led to an error on Windows Environment as seen on this issue #278 
Can you please test `npm install` on Windows?

**Comment by cstlaurent** [comment]
Yeah, it looks like the install is building the native module node-sass for node v11 because there is no native build packages for < 4.9 as seen here: https://github.com/sass/node-sass

I will look into what is referring this package and causing the issue.

**Comment by cstlaurent** [comment]
Well from what I can see there is no dependencies on node-sass, this is probably caused by another package.

image

**Pull request merged**
