### PR TITLE
Bugs fixed related to issue #1215

### LINKED ISSUE #1215: Error showing series from legend in stacked multi Chart
## Codepen
Hi, 

First of all thanks for the library and all your work!

Here is the codepen with the example:

https://codepen.io/Kylawamg/pen/mdyjVYb

## Explanation
When I use a multiseries stacked label with one line and multiple bars and multiple yaxis (see the codepen's options) the legend show / hide series feature is not working fine. Series hide or show randomly and not with his legend's icon.

Im missing something in the options object? or is a bug?

Thanks in advance!

### PR DESCRIPTION
**Pull request by tianxie1995**
# New Pull Request

Fixes #1215 

No new dependency. This bug has made me frustrated when I am working on a web app where I have a chart about Population changes and its break down components. I cannot make them both in the same chart because of the bug. Instead, I took another way to get around with it by literally creating another separate chart. If you are interested, here is the URL. https://maps.semcog.org/EconomicIndicators/#pep

### Issue 
https://codepen.io/Kylawamg/pen/mdyjVYb
In the Stacked Bar chart with line series, collapse series will result in wrong yaxis, yaxis scale, or missing yaxis. 

### Change
In `src/charts/BarStacked.js`, make sure values are available for drawing use even after collapsing some series. 
In `src/modules/Data.js`, not returning collapsed.index to preserve yaxis when stacked is true in config.
In  `src/modules/Scales.js`, make sure yaxis scale is calculating correctly by ensuring setMultipleYScales works even after the first series is collapsed.

## Type of change

Please delete options that are not relevant.

- [X] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my own code
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by tianxie1995** [comment]
Hi Juned, I have made the changes needed for merging. 

Thanks for the quick review, love the work.

**Comment by junedchhipa** [comment]
I still see the files in the `dist` directory. Please remove all the files in that directory as they are meant to be generated only during a new release.
Did you forget to push your last commit?

**Comment by tianxie1995** [comment]
Sorry about that. It's the IDE prettier which reformat the dist after rebasing it.  Now it's clear.

**Comment by junedchhipa** [comment]
@tianxie1995 
The PR broke the normal column stacked charts.
Hence, I had to revert this PR change as I published the new patch.

Please test the /samples/vanilla-js/column/ stacked charts after applying the changes. Once it looks good, I will take another look.

**Comment by tianxie1995** [comment]
@junedchhipa I have [restored changes I made](https://github.com/tianxie1995/apexcharts.js/commit/fc0f341e6f8181aea91dbefac3ed40ed7e43724a) on the StackedBar and fixed the bug on column stacked chart. Sorry for the redundant commits. 

The only thing I have done besides restoring the changes to BarStacked.js is changing [one line ](https://github.com/tianxie1995/apexcharts.js/commit/87cdfa0eddcd9e6e993f64733eea033b275decbc#diff-22c8a28e55fd1e8c77f2b6bc92f19c4eR430). 

> from `const p = Math.min(this.yRatio.length - 1, i + 1)`
> to `const p = Math.min(this.yRatio.length + 1, i + 1)`

I also added [a test sample](https://github.com/tianxie1995/apexcharts.js/commit/fc0f341e6f8181aea91dbefac3ed40ed7e43724a#diff-9a9e0cd1327d3b69e6d38a9eb6c4c53b) for a stacked bar and line.

**Comment by junedchhipa** [comment]
@tianxie1995 Thanks for the update.
Can you please create a new PR? I tried working with this same PR but I am having problems.
Thanks

**Comment by tianxie1995** [comment]
I have created a new PR #1285 regarding this. Thanks,

**Pull request merged**
