### PR TITLE
Add bar labels feature to radialBar

### PR DESCRIPTION
**Pull request by d-fischer**
This PR adds a new feature to `radialBar` charts to add labels to the individual bars. It's controlled by `plotOptions.radialBar.barLabels`.

It will take the series names as labels by default, but they can be customized using a `formatter` function.

Additionally, it updates the `circle-custom-angle` samples to use this feature to be more responsive. (We tried using the code from that very sample to make a chart and were unsuccessful in making it responsive - text was just all over the place)

This is how that example looks now:

grafik

## Type of change

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

I would appreciate help with the tests as they don't seem to run at all locally (like, even without any changes from me, they crash).

The feature should be covered by the changed `circle-custom-angle` sample though.

### CODE REVIEW

**Comment by junedchhipa** [comment]
@d-fischer Can you please add a screenshot of what the final result looks like with this addition?
Thanks for your contribution.

**Comment by d-fischer** [comment]
Updated initial post with screenshot of the changed example. Looks very similar, but does not have the markers, in turn it has a bit better alignment and much better responsiveness.

**Comment by junedchhipa** [comment]
Hey @d-fischer 
This is a very corner case and not everybody might require this. This also results in increasing the bundle size for such an edge case.
Thanks for your contribution, but I'll have to close this.

**Comment by d-fischer** [comment]
I'm not sure how this can be considered a corner case. You built an example that is not properly responsive through an absolute positioning hack with the legends. Responsiveness is one of your main selling points, so I thought I'd be doing you a favor here by improving on that main selling point in one of your examples, which we were very disappointed to see it's not responsive in the first place, like your homepage "sold" us.

As for bundle sizes, this is how it looks:
```
Build output:  dist/apexcharts.esm.js   493.45kb | 127.01kb gzipped
Build output:  dist/apexcharts.common.js   493.46kb | 127.01kb gzipped
Build output:  dist/apexcharts.min.js   493.68kb | 127.08kb gzipped
```

As opposed to the current `main` branch:
```
Build output:  dist/apexcharts.common.js   492.31kb | 126.64kb gzipped
Build output:  dist/apexcharts.esm.js   492.30kb | 126.63kb gzipped
Build output:  dist/apexcharts.min.js   492.53kb | 126.71kb gzipped
```

The difference is in the **hundreds of bytes** gzipped. Is that really a cost you are not ready to pay for improving on one of your main selling points?

**Comment by junedchhipa** [comment]
@d-fischer This is an open-source project and I am not selling anything. As an open-source user, you should understand that not all PRs can be accepted if it doesn't fit the project goals. And nobody is doing a favor to anyone in the open-source community, so please try to be respectful.

I am re-opening this PR after you posted the screenshot comparing the final build size. I will re-consider this in the upcoming releases but cannot promise it will get merged.

**Comment by d-fischer** [comment]
This is still relevant, please don't close it.

**Comment by d-fischer** [comment]
Can I do anything to help move this along?

**Comment by d-fischer** [comment]
> Can I do anything to help move this along?

**Review by junedchhipa — APPROVED** [review]

**Comment by junedchhipa** [comment]
Hey, I tried to merge this PR, but it had conflicts, so I copied all the changes and pushed a new [commit](https://github.com/apexcharts/apexcharts.js/commit/2efaaf22312b450b7a7a0730582c9f6d511dd82e) here.
The changes will be reflected in the next release.

**Pull request closed without merging**
