### PR TITLE
Add ability to use gradient fill on line and area at the same time

### PR DESCRIPTION
**Pull request by lf94**
# New Pull Request

Adds the ability to have both line and area paths fillable with a gradient (and any other fill option).

Fixes # (issue)

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by lf94** [comment]
@junedchhipa letting you know this is quite important for us (https://github.com/alephium). I'll do anything that's necessary to get this as quickly merged and published. :slightly_smiling_face:

**Review by junedchhipa — APPROVED** [review]

**Comment by lf94** [comment]
Wow thank you, that was quite fast! I truly appreciate it.

**Comment by lf94** [comment]
For what it's worth, I didn't included the built files in `dist/`. I wasn't sure about it.

**Comment by junedchhipa** [comment]
@lf94 The `dist` folder shouldn't be included. It will be generated when a new version is released.

**Comment by junedchhipa** [comment]
@lf94 Can you please share the configuration to generate the chart you attached in the screenshot?
That's a beautiful design and will go into our "popular" Codepen collections to show our users how to generate such gradients in an area chart.

**Comment by lf94** [comment]
Yeah! It's here: https://github.com/alephium/explorer/pull/91/files#diff-699e44cfab97aa2e9c65b3463d19450b50cd00907df9da4f5f256fb0d95bcec6R90

Thank you so much again for being quick with the merge...!

**Pull request merged**
