### PR TITLE
Implemented discrete markers for scatter

### LINKED ISSUE #2639: markers.discrete option is not working when using multiple scatter series
### Description
I'm visualizing multiple series of scattered data on a line chart and I would like to customize one of the dots. 
[markers.discrete](https://apexcharts.com/docs/options/markers/) sounds like a perfect candidate to implement this but unfortunately I found it to not work with multiple series of scatter type.

### Steps to Reproduce

1. Set up a basic chart of type 'line'
2. Add two series of type 'scatter'
3. Add markers.discrete option and modify one of the data points to alter its appearance.

### Expected Behavior
Dots should get customized according to the options passed in markers.discrete.

### Actual Behavior
No styles are applied to the specified dot.

### Screenshots
Screenshot 2021-09-17 at 16 28 18

### Reproduction Link
[Codepen](https://codepen.io/gruszkakarol/pen/NWgydpr)

### PR DESCRIPTION
**Pull request by brianlagunas**
# New Pull Request

Implemented discrete markers for scatter.

Fixes #2639

## Type of change

Please delete options that are not relevant.

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by junedchhipa** [comment]
We will need to keep the `pathFillCircle` as it is used for advanced fill options (like gradient/pattern in bubble charts)
If you open the 3d-bubble demo in `samples/vanilla-js/bubble/3d-bubble.html`, you will see it doesn't render anything after this change.

**Comment by brianlagunas** [comment]
So what kind of logic can I use to determine if we need to apply the pathFillCircle or the markerConfig Fill?

**Comment by junedchhipa** [comment]
Yeah, I am looking at the code, and I probably made a mistake when combining both.
markerConfig is used to get certain properties (height/width/radius/shape/color), while pathFillCircle is only used for the fill option.
When we call `fillPath` function, we can also send `color` in the options so that color gets applied.
Let me also test it first

**Comment by junedchhipa** [comment]
@brianlagunas Your code helped me to dig the root of the cause. However, I will open a new PR because I had to refactor some code and do some cleanup to the older code.

**Comment by brianlagunas** [comment]
Sounds good! I will close this PR and wait to review yours so I can better learn the code base.

Thanks!

**Pull request closed without merging**
