### PR TITLE
Handle click on label

### LINKED ISSUE #2324: Click on datalabel should give dataPointIndex
**Is your feature request related to a problem? Please describe.**	
I have a column chart similar to sample distributed-columns. 
But as we have large differences in numbers (one column can have value 2 and another value 13000) then the small columns are not visible. So we have a dataLabel on top with and offset. 
We need to have the columns clickable and for usability also the labels. But I don't get the dataPointIndex in the clickevent. I get it for the columns but not the dataLabel.

**Describe the solution you'd like**	
I would like the dataPointIndex to be included in the event when clicking on dataLabel the same way as it is when clicking on the column.

**Describe alternatives you've considered**	
I have tried different solutions to hook up listners and so but I can't get it to work and I do only have the value of the column, not the serie or the id for the column.
Alternative would be to use some other chart. But apexchart has been top notch otherwise for me.

**Additional context**	
image

### LINKED ISSUE #3038: Clickable annotations
## Summary

Making annotations clickable and knowing which annotation by getting for example its xaxis index and/or timestamp would be very handy for some use cases.

## API Changes

For example introduce an event called annotationClick() which allows to access different properties of that annotation **as well as its y or x axis index or timestamp to be able to identify them**.

## Intended Use Case

There are anomalies marked with annotations. A click would allow to validate them or add some additional text information.

### PR DESCRIPTION
**Pull request by alik0211**
# Handle click on label

I have added a click event for x-axis labels. The event provides information about a `labelIndex` (in most cases, it corresponds to the ``dataPointIndex`` from event `click`)

image

## Type of change

Please delete options that are not relevant.

- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by brianlagunas** [comment]
Have you testing this feature with the other chart types?

**Comment by alik0211** [comment]
Yes. This only works for horizontal bars.

**Comment by brianlagunas** [comment]
Thank you for the PR, but we cannot accept a feature that only works for one chart type. If you would like to add support for all other chart types, please update this PR. Otherwise I will have to close it. Let me know what you would like to do.

**Comment by alik0211** [comment]
I have added support for other chart types. The PR has been updated.

**Comment by junedchhipa** [comment]
`labelClick` is a vague name that can mean any kind of label click. We have x-axis labels, data labels, annotations, etc.
Please rename the property to `yAxisLabelClick` to make it more meaningful.

**Comment by alik0211** [comment]
Good point, thank you! Renamed to `xAxisLabelClick` because it is an event for the x-axis labels.

**Comment by trylaarsdam** [comment]
Does this actually fix #3038? It seems like this PR only provides a click handler for x-axis labels, not annotations. Maybe I missed something though.

**Comment by alik0211** [comment]
I'm sorry, apparently I got the annotations and labels mixed up

**Comment by alik0211** [comment]
@junedchhipa what else do I need to get approved?

**Comment by alik0211** [comment]
I have made as few changes as possible to add this functionality.

**Review by junedchhipa — APPROVED** [review]

**Pull request merged**
