### PR TITLE
fix: typos in svgjs section of apexcharts

### PR DESCRIPTION
**Pull request by kkirsche**
# New Pull Request

This is the first pull request that addresses misspellings found throughout the codebase. This pull request explicitly focuses on the svgjs portion of the apexcharts.js library. I will do other sections later, but I wanted to begin with a smaller, more focused changeset.

```
src/svgjs/svg.js:288: convertions ==> conversions
src/svgjs/svg.js:610: convertions ==> conversions
src/svgjs/svg.js:880: trough ==> through
src/svgjs/svg.js:1100: positon ==> position
src/svgjs/svg.js:1334: occured ==> occurred
src/svgjs/svg.js:1384: shouldnt ==> shouldn't
src/svgjs/svg.js:1406: trough ==> through
src/svgjs/svg.js:2479: convertion ==> conversion
src/svgjs/svg.js:2577: convertion ==> conversion
src/svgjs/svg.js:3413: retuns ==> returns
src/svgjs/svg.js:3463: aliasses ==> aliases
src/svgjs/svg.js:3482: aliasses ==> aliases
```

Fixes # (issue)
N/A

## Type of change

- [X] Bug fix (non-breaking change which fixes an issue)

Typos

## Checklist:

- [X] My code follows the style guidelines of this project
- [X] I have performed a self-review of my code
- [X] I have commented on my code, particularly in hard-to-understand areas
- [X] My changes generate no new warnings
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] New and existing unit tests pass locally with my changes

### CODE REVIEW

**Comment by kkirsche** [comment]
Ah, this broke some of the others, I'll re-create and avoid that. Sorry about that, seems my automation broke a few other whitespace items

**Comment by kkirsche** [comment]
Seems I don't have any editors that don't trigger these wider whitespace clean ups so I cannot address those for you directly, sorry.

**Comment by kkirsche** [comment]
These appear to be the remaining typos based on what I could find:

```
src/apexcharts.js:436: serie ==> series
src/charts/RangeBar.js:104: possiblity ==> possibility
src/charts/common/line/Helpers.js:133: serieses ==> series
src/libs/Treemap-squared.js:184: everytime ==> every time
src/libs/Treemap-squared.js:225: comparision ==> comparison
src/modules/Scales.js:482: serie ==> series
src/modules/Scales.js:483: serie ==> series
src/modules/Scales.js:492: serie ==> series
src/modules/Scales.js:492: serie ==> series
src/modules/Scales.js:492: serie ==> series
src/modules/Scales.js:498: serie ==> series
src/modules/ZoomPanSelection.js:668: continuosly ==> continuously
src/modules/Data.js:497: overrided ==> overrode, overridden
```

**Comment by brianlagunas** [comment]
thanks for the PR, but we aren't too concerned with typos.

**Comment by kkirsche** [comment]
:/ that's concerning, but ok

**Comment by brianlagunas** [comment]
The typos you PR addressed were in the comments of the svg.js file which is not a file that we write or maintain. It also contained a ton of formatting changes.

The typo in the scales.js file are not part of the public API and not important enough to require a "fix".

Other typos in the internal code comments are not something that should be concerning.

**Pull request closed without merging**
