### PR TITLE
removes unnecessary update when window height changes

### PR DESCRIPTION
**Pull request by FunkiR**
# New Pull Request

Hi, I am using graphics inside an iframe that dynamically changes its height. This triggers the resize event and all charts start updating. Is such a solution to this problem possible?

## Type of change

- [x] Bug fix (non-breaking change which fixes an issue)

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] My changes generate no new warnings

### CODE REVIEW

**Comment by junedchhipa** [comment]
There is a property `chart.redrawOnParentResize` which can be turned off if you don't want the charts to be updated on parent window resize. Try and let me know if it works.

**Comment by FunkiR** [comment]
No, this property is used in _parentResizeCallback, but I need to remove the height triggering in windowResizeHandler.
```javascript
window.addEventListener('resize', this.windowResizeHandler)
window.addResizeListener(
     this.el.parentNode,
     this._parentResizeCallback.bind(this)
)
```

**Comment by junedchhipa** [comment]
Ok, can you test if your code doesn't turn off the actual behavior?
Try placing the chart in a container, and only resize that parent (not window).
If possible, please show a GIF that does that.

**Comment by FunkiR** [comment]
Everything works, but I don't like my first solution) Could it be better to add the redrawOnWindowResize property? Here is a [example](https://codepen.io/funkir/pen/JjKrLZq)

**Comment by junedchhipa** [comment]
Thanks for providing an alternative.
This looks better. I will merge soon.

**Pull request merged**
